---
- name: runit restart {{ runit_service_name }}
  shell: sv restart {{ runit_service_name }}
  become_user: "{{ runit_service_user }}"
  environment:
      SVDIR: /etc/service

- name: runit hup {{ runit_service_name }}
  shell: sv hup {{ runit_service_name }}
  become_user: "{{ runit_service_user }}"
  environment:
      SVDIR: /etc/service

- name: runit reload {{ runit_service_name }}
  shell: sv reload {{ runit_service_name }}
  become_user: "{{ runit_service_user }}"
  environment:
      SVDIR: /etc/service

- name: runit restart {{ runit_service_name }}/log
  shell: sv restart {{ runit_service_name }}/log
  environment:
      SVDIR: /etc/service

- name: runit hup {{ runit_service_name }}/log
  shell: sv hup {{ runit_service_name }}/log
  environment:
      SVDIR: /etc/service

- name: runit reload {{ runit_service_name }}/log
  shell: sv reload {{ runit_service_name }}/log
  environment:
      SVDIR: /etc/service
